AutoQC.py

This is an example of what an output plot might look like. At the moment only one point is shown but when implemented fully there would be points for every combination of quality control tests. I don't know if it is worth merging this now, but I thought it would be useful to produce this as an example.

A basic example of how an output plot might look

---

AutoQC.py

- wrapped @s-good 's recent plotting routine in a function
- moved function comments to docstrings, more pythonic

tidying up

---

AutoQC.py
qctests/Argo_global_range_check.py
qctests/Argo_gradient_test.py
qctests/Argo_pressure_increasing_test.py
qctests/WOD_gradient_check.py
qcvalidation.py
util/testingProfile.py

I'll be pushing checks on the qc tests to this branch as I write them over the next little while, as was discussed in #46. I can write checks and profiles that will obviously be flagged by the qc tests to validate gross behavior, but one thing that would be helpful would be if @s-good would describe some more subtle or realistic scenarios of profiles that should be getting flagged. Comment here and I'll implement.

QC test validation

---

qctests/Argo_global_range_check.py
qctests/EN_range_check.py
qctests/EN_spike_and_step_check.py
qcvalidation.py
util/testingProfile.py

This is a first attempt at #28. More testing is needed and the code will need to be changed in future when #56 gets implemented.

EN spike and step check

---

qctests/EN_spike_and_step_check.py
qcvalidation.py

This PR begins examining the EN_spike_and_step test in greater detail. Some thoughts:
- biggest refactor is in moving as much of the qc test out into helper functions as possible, so that we can test conditions separately; this is crucial here, so we can test the main conditions for flagging (A-C) independently, and not conflate their behavior.
- validation tests are currently incomplete; need to test condition C and some of the smaller helper functions.
- it's not immediately obvious from the reference text what `wt1` is. @s-good, is this an extension of this qc test beyond what's defined in the reference?

began refactor & testing for `EN_spike_and_step`

---

AutoQC.py
data/EN_bgcheck_info.nc
dataio/wod.py
qctests/Argo_global_range_check.py
qctests/Argo_gradient_test.py
qctests/Argo_impossible_date_test.py
qctests/Argo_impossible_location_test.py
qctests/Argo_pressure_increasing_test.py
qctests/Argo_regional_range_test.py
qctests/Argo_spike_test.py
qctests/EN_background_check.py
qctests/EN_constant_value_check.py
qctests/EN_range_check.py
qctests/EN_spike_and_step_check.py
qctests/WOD_gradient_check.py
util/obs_utils.py

Implements the EN background check #56. NB. it requires a data file to operate. I need to work out how to distributed the data file. If it is not present the test is effectively ignored.
This also includes an attempt to solve #62.

EN background check

---

qcvalidation.py

adds `suspect` logic to tests for `EN_spike_and_step`. Note one test still fails due to my line note in #63.

cleaned up tests after #63

---

tests/wod_tests.py

nose test discovery compliance

testing bugfix

---

AutoQC.py
tests/util_tests.py
util/main.py

- moved most of the rest of main's helper functions out to `main.py`; remaining couple are slightly more delicate
- moved util testing into the new `tests/`

more cleanup

---

.travis.yml
requirements.txt

Here are the files we'll need for continuous integration with travis.

getting ready for CI

---

dataio/README.md
dataio/wod.py

corrects & pulls out the key docs for the WOD decoding class into an easily digestible README.md. This is (hopefully) a useful guide for new contributors.

docs for the `WodProfile` class

---

README.md
tests/obs_utils_tests.py
util/obs_utils.py

added some basic tests for the `obs_utils` helpers, as part of the testing I suggested to finish #56 - mostly checks the suggested check-values from the text.

testing obs_utils

---

AutoQC.py
datafiles.json
tests/SVMtests.py
tests/main_tests.py
util/main.py
util/svmClassifier.py

this PR doesn't make any crucial changes, but provides a taggable state to base some learning analysis on.

tagging a version for svm analysis

---

learningAnalysis/basic-machine-learning/Hsu-Chang-Lin.ipynb
learningAnalysis/basic-machine-learning/Untitled.ipynb

Added some notes taking a quick stab at [this paper's suggestions](http://www.csie.ntu.edu.tw/~cjlin/papers/guide/guide.pdf) for using SVMs. No great improvements were identified, but adding the notes anyway for future reference.
Also note, rerunning the previous notebook from #101 produced different results for the SGD - probably an effect of randomization; should likely avoid this technique until this is better understood.

quick exploration of Hsu, Chang and Lin

---

AutoQC.py
cotede_qc/cotede_test.py

Added checking for invalid day and time in cotede_test.py.
Also removed unused modules from AutoQC.py.

Improved robustness for cotede_test.py.

---

AutoQC.py
datafiles.json
tests/main_tests.py
util/main.py

just wrapping @s-good's array combination from #118 in a function and setting a unit test so we can set those concerns aside permanently.

test array combination infrastructure

---

qctest_requirements.json
qctests/EN_increasing_depth_check.py
tests/EN_increasing_depth_check_validation.py

Implements the EN increasing depth check.

Introduced EN_increasing_depth_check.

---

.travis.yml
requirements.txt

This introduces changes by @castelao to the list of requirements.

Updates to requirements with CoTeDe dependencies

---

.travis.yml

currently the travis build is checking the master branch instead of the new commits it should be checking; this will hopefully fix the problem.

fix for travis build problems

---

qctests/ICDC_aqc_08_gradient_check.py

Minor update to the docstring so that it matches the file provided by ICDC.

Updated docstring for ICDC test 8.

---

README.md

a few tuneups to AWS setups and dep links

readme tidyup

---

tests/wod_tests.py

stopping wod test from breaking when datafiles.json changes

---

docker/Dockerfile

one cotede test was never getting run due to the absence of scikit-fuzzy.

scikit-fuzzy in docker image

---

README.md

The markdown in the below sections of the README.md were not having the desired effect:
* Introduction
* Usage 
* Testing
Corrected the sections so that the markdown has the desired effect

Correcting the markdown in the README.md

---

qctests/EN_increasing_depth_check.py

#220 improved the scaling performance of `EN_increasing_depth` check by not computing the full matrix of depth comparisons more than once; however, even computing this once was still taking ~10s on my machine for large profiles. This PR better leverages numpy to drop the computation of an entire row at a time into the underlying C, speeding up this matrix computation by an order of magnitude.

speed up computation of increasing depth matrix

---

qctests/AOML_spike.py
tests/AOML_spike_check.py

AOML's spike check.
quickie XBT perf check:
```
NAME OF TEST   FAILS     TPR     FPR     TNR     FNR
Truth   10172  100.0%    0.0%  100.0%    0.0%
AOML_spike   19088   53.8%   23.9%   76.1%   46.2%
```

first pass at aoml spike check

---

qctests/AOML_climatology_test.py
tests/AOML_climatology_check.py
util/AOMLinterpolation.py
util/AOMLnetcdf.py

work in progress - still need to write some unit tests for this, and tidy up some more, but the bulk of the implementation is visible here.

first pass at aoml climatology

---

qctests/AOML_gross.py
tests/AOML_gross_check.py

xbt run:
```
NAME OF TEST   FAILS     TPR     FPR     TNR     FNR
Truth   10172  100.0%    0.0%  100.0%    0.0%
AOML_gross    2186   21.4%    0.0%  100.0%   78.6%
```

AOML gross check

---

tests/EN_track_validation.py

Thanks to @s-good for catching this!

remove old datastore package from en_track unit testing

---

build-db.py

@s-good this should preserve all the functionality of your recent contributions to `build-db.py`, but refactors just a little:
- I like to avoid functions being defined inside other functions unless really necessary
- Pulls config out to command line arguments, so we can avoid having an ever-growing list of configuration options in the builder. So to run configured for quota, you would do:
```
python build-db.py quota.wod tablename False 1,2,3,6
```

refactor build db

---

.travis.yml

patch environment for new icdc climatology

---

cotede_qc/cotede_test.py
cotede_qc/qc_cfg/cotede10.json
cotede_qc/qc_cfg/cotede12.json
cotede_qc/qc_cfg/cotede15.json
cotede_qc/qc_cfg/cotede18.json
cotede_qc/qc_cfg/cotede20.json
cotede_qc/qc_cfg/cotede25.json
cotede_qc/qc_cfg/cotede5.json
install.sh

CoTeDe configuration format changed requiring to conform cotede_test.py
@BillMills & @s-good , I released a new patch for CoTeDe and I believe that I fixed everything in the cotede_test.py for AutoQC. I didn't manage to build my Docker so I could run a full test. If it needs more changes, I might take a few days to be able to respond again.
Cheers,

Conforming to new CoTeDe config pattern

---

.zenodo.json

Per @castelao's request in #268 .

correct cotede doi

---

.travis.yml
install.sh

exactly the same as #273, but re-opened to try and kick off the new travis integration.

package upgrade in testing environment

---

tests/dbutils_validation.py
util/dbutils.py

Exact same change as in #271, just cleaning up the already-merged commits.

test db_to_df batching

---

catchall.py

Per the discussion at https://github.com/IQuOD/AutoQC/pull/270/files#r644709834, looks like maybe this correction didn't make it in and we missed it at the time.

corrections to db management in catchall
