AutoQC.py
Started adding some simple assertion checks to the functions used in `AutoQC.py`, when I came across something I don't understand. The `assert` I have written for `refereceResults` insists that all reference results be numpy booleans; this assertion raises exceptions, since several of them are of type `<class 'numpy.ma.core.MaskedConstant'>`. This may in fact be correct, but my misunderstanding - @s-good, do you know why we'd be getting masked constants and not `True` or `False` for some of the reference results?
If indeed all is well, let me know before merging this pull, and I'll amend it with a more appropriate assertion test.
=> began adding simple asserts to functions in AutoQC.py

qctests/Argo_spike_test.py
Here's a run at the Argo spike test for temperature, requested in #25 - a couple of things to note:
- I took the issue dead literally, by interpreting pressure in db described in the reference as depth in meters.
- This test will always pass the first and last measurements in a profile, since the spike test relies on having a measurement both before and after.
- This test demands that both temperature and depth info be available for the measurement in question, as well as the temperature one step before and one step after (for the purposes of calculating the spike). If any of these demands are not satisfied, no exception is raised for that measurement.
=> first pass at Argo spike for #25

qcvalidation.py, util/testingProfile.py
As I was mentioning in #41, we'd like to be able to run some sanity checks on our implementations of the qc-tests, particularly for the more sophisticated ones like in #28. `util/testingProfile.py` creates a dummy class that mimics the WOD profile class, into which can be passed arbitrary arrays of temperature and depth data to create fake profiles designed to pass or fail a given qc test.
running `nosetests qcvalidation.py` at top level will run this validation; currently only one trivial check is implemented, but if the strategy seems sound we can go ahead and implement more serious validation checks.
=> illustrates proposal for qctest validation suggested in #41

AutoQC.py, qctests/Argo_gradient_test.py, qctests/WOD_gradient_check.py
This PR contains first passes at the checks in #26 and #27. Notes:
- Both follow the previous implementation of `Argo_spike_test.py` and its assumptions.
- `WOD_gradient_check.py` adds a constraint that demands the depths of neighboring measurements not be identical (in order to avoid dividing by 0 in the gradient). But, the text mentions requiring neighboring measurements be separated by at least 3 m in the case of high-resolution instruments; that would also solve the divide-by-0 problem, but it isn't immediately clear to me if this constraint can be required generally, or, perhaps better, if and how the profile object indicates whether it was a 'high resolution' measurement or not.
- Turned off the verbose logging temporarily, as the combinatorics grow. 
- `WOD_gradient_check.py` also …
=> Gradient Tests

tests/qcvalidation.py
Per the line-note discussion in #63, tropical temperatures are flagged as suspect by `EN_spike_and_step` - this patches the test suite; all tests currently passing.
=> tropical temps are suspect flags only in EN_spike_and_step

.travis.yml
this is the travis build script from #79 - merging it in ahead of that work, since the anaconda install is several minutes faster than pip'ing everything.
=> faster travis build

qctests/Argo_impossible_date_test.py, tests/Argo_impossible_date_test_validation.py, util/testingProfile.py
Implemented the time check on `Argo_impossible_date` from #51 - but, I'm a little unclear on how the wod format is encoding times. It looks like times are floats on the range 0 to 24, so the condition in the [text](http://w3.jcommops.org/FTPRoot/Argo/Doc/argo-quality-control-manual.pdf) that requires a plausible hour and minute are interpreted here as the time returned from the profile being on that range. Let me know if there's a problem with this interpretation.
=> Impossible date time

AutoQC.py, qctests/EN_stability_check.py, tests/EN_stability_check_validation.py
this PR adds the requisite helper for EN-stability (in pursuit of #64 ), and drops an old dependency from the main routine.
=> started on EN-stability

qctests/EN_stability_check.py, tests/EN_stability_check_validation.py, util/testingProfile.py
This PR implements & tests EN_stability. A few concerns:
- [the text](http://www.metoffice.gov.uk/hadobs/en3/OQCpaper.pdf) describing the test was a bit hard to follow; I assumed that the test for density spikes proceeded if and only if the first threshold failed (delta rho < -0.03 kg/m3) - otherwise, the subsequent spike check would always flag every level.
- McDougall refers to salinity measured in psu, but the WOD definition document reports salinities as unitless; is there a unit conversion that needs to be done?
In other news - this completes all outstanding qc tests save the track check. The one clear result coming from our early machine learning study, is that we don't have enough qc tests implemented yet to make a final qc decision. With our current set of qc tests, about half of …
=> first pass at en-stability

AutoQC.py, datafiles.json, util/splitData.py
In order to take advantage of powerful computing clusters like EC2 (see #105), it was necessary to parallelize AutoQC's operation. Running AutoQC in a single thread and running it with this parallelization scheme over the full *quota* dataset produced the exact same results in section 0.3 of the basic machine learning study previously discussed, confirming correct behavior. To configure the degree of parallelization, change `pool = Pool(processes=4)` in `AutoQC.py` to the number of processors available.
Furthermore, in order to avoid unnecessary runs over datasets, this PR also concludes `AutoQC.py` by writing results to a CSV, rather than immediately drawing plots or doing analyses; this post processing should be done by a separate script, so it isn't necessary to re-process all the raw …
=> Parallelization

qctests/CSIRO_gradient.py
Implements an interpretation of the CSIRO gradient test described in [the paper](http://journals.ametsoc.org/doi/abs/10.1175/JTECHO539.1) recommended by @BecCowley. A few comments:
- instead of making any replacements per the text, profiles with suspicious characteristics are simply flagged for further inspection, per our priority of minimizing false negatives.
- I assumed the wire break criteria only applied to XBT probes, but I may have misinterpreted the text; let me know.
- the spike check suggested in the text is not yet implemented; the exact algebraic definition of a spike was not immediately obvious from the text. Will try to deduce from the fortran.
This test seems simple enough that attempting to wrap the FORTRAN seemed unnecessary. Interestingly, even though we already have two …
=> added CSIRO gradient test

AutoQC.py, data/ds.py, qctests/Argo_global_range_check.py, qctests/Argo_gradient_test.py, qctests/Argo_impossible_date_test.py, qctests/Argo_impossible_location_test.py, qctests/Argo_pressure_increasing_test.py, qctests/Argo_regional_range_test.py, qctests/Argo_spike_test.py, qctests/EN_background_check.py, qctests/EN_constant_value_check.py, qctests/EN_range_check.py, qctests/EN_spike_and_step_check.py, qctests/EN_stability_check.py, qctests/WOD_gradient_check.py, qctests/WOD_range_check.py, tests/EN_background_check_validation.py, tests/main_tests.py, util/main.py
This PR makes some (hopefully final) infrastructural tweaks as we approach v1 by mid 2016:
- kwargs arguments are dropped in favor of parameter stores encapsulated along with the relevant test; see `EN-background` for an example
- a couple more infrstructural unit tests are added to ensure parallelization and CSV construction functions are proceeding as expected.
- CSV now uses profile `uid()` as primary key (instead of just numbering the rows)
- some usage help has been added
- plus a few trivial tidy-ups.
There shouldn't be anything too controversial about this PR, I'm going to give it until Friday and merge it then if there are no problems.
=> Infrastructure tweaks

AutoQC.py, util/main.py
The output to screen was not working well when running in parallel as messages were printed to screen for each file that was processed rather than for the full results. These changes are aimed at improving this and the percent process indicator has been removed - I may try to reincorporate this in future as I found it quite useful to track progress.
In the course of doing this I noticed that only the output from the first file processed was being written to the csv file and I've tried to fix this.
I have removed the logfile writing function as this is now unused and was previously found to be very slow.
It may be better in future to read the profile list in the main function like is now done for the list of QC checks so that the QC checks can see all the profiles rather than just the ones …
=> Tidying up output when using parallel running

AutoQC.py, qctest_requirements.json, qctests/EN_background_available_check.py, qctests/EN_background_check.py, tests/EN_background_available_check_validation.py, util/main.py
catchFlags was being applied before the check that there were temperature data in a profile.
Recent results suggested that rejected levels where the EN background is not defined may not be the best approach so this is separated out.
=> Fix order of applying the catchFlags function and separate out an aspect of the EN background check

.travis.yml
As discussed in #120, it is not necessary to have the line installing the seabird package in the travis configuration.
=> Removed install of seabird from the travis config file.

AutoQC.py, qctests/EN_std_lev_bkg_and_buddy_check.py, tests/EN_std_level_background_check_validation.py, util/testingProfile.py
This PR will contain several updates to the buddy check and related infrastructure, per discussion in #133. Todo:
- ~~Slice up buddy check into shorter helper functions~~
- ~~Test buddy check helpers~~
- Persist all qc results for `EN` tests to avoid rerunning
- ~~Address some small issues with the buddy check:~~
- ~~use the datastore module for passing global variables, rather than importing `__main__`~~
- ~~currently throws a complaint:~~
```
/opt/conda/lib/python2.7/site-packages/numpy/ma/core.py:4089: UserWarning: Warning: converting a masked element to nan.
warnings.warn("Warning: converting a masked element to nan.")
```
~~which seems ominous - should be addressed.~~
Before tackling upgrades like using the datastore and persisting qc, the first two bullets need to get done to ensure …
=> buddy check tune up

qctests/ICDC_aqc_07_spike_check.py
The ICDC spike check was initially implemented using a loop over depths. However, this was unnecessary as the calculation could be done as vectors.
=> Removed loop and implemented as vector calculations.

cotede_qc/cotede_test.py
Minor bugfix. It shouldn't compromise the previous results.
=> BUGFIX #141, missing a round to define the seconds.

AutoQC.py, cotede_qc/cotede_test.py
This pull request has two fixes:
1. I realised that now that the list of profiles is read in the main program, when running in parallel each process will attempt to QC the whole set of profiles. I've introduced a fix for this, although it is possibly not the most elegant solution!
2. A temporary fix to prevent 60 seconds being passed to datetime. This is just so that the processing will run until a more permanent fix is implemented.
=> FIx running in parallel and temporary datetime fix

AutoQC.py, qctests/EN_track_check.py, tests/EN_track_validation.py, tests/geo_tests.py, tests/main_tests.py, util/geo.py, util/main.py
I'll be pushing progress on #54 to this pull request; still a long way to go, but some of the strategy is visible right now.
Unlike all the other qctests, `EN_track` requires all the profiles from a given cruise all at once. But, for performance, we don't want to load any given profile more than once. In order to approach this, I'm trying the following:
- after loading the full list of profile primary headers, sort by cruise number.
- instead of running the full suite of tests after loading each individual profile, load an entire cruise worth of profiles, make them available on the global data store, then run each test individually exactly as previous, profile by profile.
- have `EN_track` write a copy of its results to the global data store. This way, the first time `EN_track` is called …
=> EN_track_check

README.md, docker/Dockerfile
The climatology test at CoTeDe was updated to WOA13. If not available, the required files are automatically downloaded, but if we include those into the docker it could save quite some time, and bandwidth.
Would that be fine to include those files with the docker?
=> Climatology test with WOA13

AutoQC.py, qctests/EN_track_check.py, tests/EN_track_validation.py, util/geo.py
This pull request fixes a couple of issues I found when running the EN track check on the full QuOTA dataset:
- util/geo.py needs to handle missing data when creating datetime instances.
- The test crashes if number of data files > number of threads because the EN_track_headers variable is not {} after the first file is processed in the thread. I've attempted to fix this by saving the data file name and updating EN_track_headers when this changes.
=> Fixes for runtime errors when running EN track check.

qctests/EN_increasing_depth_check.py, tests/EN_increasing_depth_check_validation.py
as per the discussion in #157, `EN_increasing_depth` now starts by checking if all levels are the same, and flags them all and returns immediately if so.
=> fixes #157

qctests/Argo_global_range_check.py, qctests/Argo_gradient_test.py, qctests/Argo_pressure_increasing_test.py, qctests/Argo_spike_test.py, tests/Argo_global_range_check_validation.py, tests/Argo_gradient_test_validation.py, tests/Argo_pressure_increasing_test_validation.py, tests/Argo_spike_test_validation.py, tests/obs_utils_tests.py, util/obs_utils.py
Argo tests are designed to work on pressure so this change corrects the previous implementation. GSW (Python version of the TEOS-10 software) is now used for depth-pressure conversion.
=> Change Argo tests to work on pressure instead of depth.

docker/Dockerfile
This fixes two issues:
- the `.bashrc` @castelao requested was not getting included properly before (my mistake from #159 )
- since last I checked, `woa13_decav_s13_5dv2.nc` through `s16` are downloaded if unavailable; these are now in the docker image.
The image on dockerhub already reflects these changes.
=> fixed bashrc inclusion in dockerfile, added some more data

qctests/CSIRO_constant_bottom.py, tests/CSIRO_constant_bottom_validation.py
patches edge case where `CSIRO_constant_bottom` would error out on a profile with only a single level.
=> fix CSIRO_constant_bottom edge case

qctests/EN_background_check.py
`EN_background` was complaining about non-integer array indices, threatening a deprecation in future; typecasting indices to ints shouldn't cause any problems.
=> futureproof against numpy warning

cotede_qc/cotede_test.py
Attempt to fix #173. Latest version of the code preferentially runs a single test at a time rather than a set of tests. Change makes the code check whether the result of the required test is in memory.
=> Fix key error

qctests/CoTeDe_Argo_density_inversion.py, qctests/CoTeDe_GTSPP_WOA_normbias.py, qctests/CoTeDe_GTSPP_global_range.py, qctests/CoTeDe_GTSPP_gradient.py, qctests/CoTeDe_GTSPP_profile_envelop.py, qctests/CoTeDe_GTSPP_spike_check.py, qctests/CoTeDe_Morello2014.py, qctests/CoTeDe_WOA_normbias.py, qctests/CoTeDe_anomaly_detection.py, qctests/CoTeDe_digit_roll_over.py, qctests/CoTeDe_fuzzy_logic.py, qctests/CoTeDe_gradient.py, qctests/CoTeDe_location_at_sea_test.py, qctests/CoTeDe_rate_of_change.py, qctests/CoTeDe_spike.py, qctests/CoTeDe_tukey53H_norm.py
wraps cotede tests in a try / except so if anything goes wrong, no flag is raised and qc continues smoothly.
In response to #184, though does not address the fundamental issue upstream in cotede pointed out there.
=> allow cotede tests to gracefully fail

AutoQC.py, qctests/EN_std_lev_bkg_and_buddy_check.py, tests/EN_std_level_background_check_validation.py, util/main.py
db interactions, particularly in the parallel part of the code, should be governed by `util/main.py: dbinteract(command)`.
=> Stabilize db

.travis.yml, AutoQC.py, docker/Dockerfile, launchQC.sh, util/main.py
This PR replaces #191, with the key update that bashrc files are not run when not logging into a docker container interactively, which is the case on Travis; therefore, environment variables must be set in the Dockerfile. Note the new Docker image hasn't been pushed at the time of this writing (so tests will still be failing), but should become available in about an hour.
=> Process-level parallelization II

qctests/CSIRO_short_gradient.py, qctests/EN_increasing_depth_check.py
In addition to addressing #200, also patches the divide by 0 problem in `CSIRO_short_gradient` first identified by @s-good in #195.
=> fixes #200

qctests/EN_track_check.py
forces consistent ordering of profiles on a cruise, even when timestamps are identical, by subsequently sorting by uid.
=> fixes #204

tests/geo_tests.py, util/geo.py
at least a partial response to the discussion in #209:
- Avoids the use of `archaversine` when calculating angles between track segments, and the corresponding pathology, by using the analogous spherical law of cosines instead, with enforcement of [-1,1] arguments for arccos.
- Doesn't actually do anything about archaversine itself; as I said in #209, I think that function should complain about negative arguments, since (non-imaginary) haversines should always be positive.
=> correct and protect course correction angle calculation

AutoQC.py, build-db.py, qctests/CoTeDe_Argo_density_inversion.py, qctests/CoTeDe_GTSPP_WOA_normbias.py, qctests/CoTeDe_GTSPP_global_range.py, qctests/CoTeDe_GTSPP_gradient.py, qctests/CoTeDe_GTSPP_profile_envelop.py, qctests/CoTeDe_GTSPP_spike_check.py, qctests/CoTeDe_Morello2014.py, qctests/CoTeDe_WOA_normbias.py, qctests/CoTeDe_anomaly_detection.py, qctests/CoTeDe_digit_roll_over.py, qctests/CoTeDe_fuzzy_logic.py, qctests/CoTeDe_gradient.py, qctests/CoTeDe_location_at_sea_test.py, qctests/CoTeDe_rate_of_change.py, qctests/CoTeDe_spike.py, qctests/CoTeDe_tukey53H_norm.py, qctests/EN_background_check.py, qctests/EN_spike_and_step_check.py, qctests/EN_track_check.py, qctests/ICDC_aqc_01_level_order.py, qctests/ICDC_aqc_09_local_climatology_check.py, tests/EN_track_validation.py, tests/ICDC_aqc_09_local_climatology_check_validation.py, util/main.py
This PR presents a number of modifications to out sqlite3-backed implementation, both to better support parallelization, and address some other issues that became apparent while resolving this:
- The parallelization problems we were facing were due to difficulties with python's netCDF package in parallel read environments (see https://github.com/Unidata/netcdf4-python/issues/640, https://github.com/Unidata/netcdf4-python/issues/437). Reading `ICDC_09`'s parameter file in the child process resolves this issue.
- Very generous tolerances are allowed for database connection timeouts (60 seconds) and retries (100). This is necessary to accommodate sqlite's single-writer behavior.
- Implements a simple logging infrastructure. Each profile will persist a separate log of its stdout and stderr …
=> addressed parallelization issues with sqlite db backing

util/dbutils.py
Turns out that python's built-in `sum` and numpy's summation function return different results when summing up masked arrays with some-but-not-all the entries masked:
```
In [43]: m = np.ma.array([3,4,10], mask=[True, True, False])
In [45]: sum(m)
Out[45]: masked
In [46]: np.sum(m)
Out[46]: 10
```
This was messing up our assessment of whether there were any true QC flags in our `dbutils` package.
=> protect against missing data when summarizing true qc decisions

build-db.py
Now that we use uid as a formal primary key when building our initial database in `build-db.py`, we must deal with the situation where a duplicate profile appears in the raw wod-ascii data (as one does in my copy of the full quota set). Here we keep track of what uids have been previously written to the database, and skip any subsequent repeats.
=> protect against duplicate profiles when building db

build-db.py, util/dbutils.py, util/main.py
It seems that 99.99, in addition to 99.9, has been used as a mask; see UIDs 66424634, 66424635, 66424645, 66425567, 66425571 for example. The UID's mentioned make up about half the false positives in the optimal point of the ROC curve I'm currently looking at, so this seems impactful; @s-good let me know if a temperature of 99.99 is indeed to be masked as I assume, or if it means something more nuanced.
=> Handling temperature 99 error codes

qctests/EN_increasing_depth_check.py
The current implementation of `EN_increasing_depth` scales very badly (as bad as n^3) in number of profile levels, due to the recomputation of the entire nxn matrix of level comparisons, as many as n times as each level is examined. This causes profiles with a large number of levels (see uid 86124230 with ~8000 levels) to take an enormous amount of time.
If I've understood the algorithm correctly, it shouldn't be necessary to recompute the entire matrix at every iteration; when a level becomes flagged by this test, it should only be necessary to recompute the corresponding row and column of the comparison matrix, dropping the execution time to n^2 instead of n^3. This PR implements that change; @s-good please examine critically as this is a non-trivial refactor of this test.
=> improve performance of EN_increasing_depth

AutoQC.py, analyse-results.py, build-db.py, plot-roc.py, util/dbutils.py
This PR contains a number of infrastructural odds and ends developed while analyzing QuOTA:
`build-db.py`
- adds a 'training' column into the db to keep track of which profiles are being used for algorithm training
- filters out (in addition to previous filters):
- profiles expressed in standard levels
- profiles with depth approx 0 for all levels (lots of these in quota)
- profiles with corrupt or missing originator temperature qc decisions at any level that has a nominally valid temperature reading
`db-utils.py`
- Add uid to dataframe in `db_to_df`, and explicitly randomize selection when unpacking less than the whole database.
- `summarize_truth` makes sure not to count masked qc levels when summarizing per-level flags; addresses edge case where a masked level would be cast to nan, …
=> Sample construction, truth summarization and ROC calculation and plotting

qctests/EN_background_check.py
By transforming depths to pressures for every level in the profile all at once in `en_background`, we can take better advantage of `gsw`'s optimizations (it's really quite well written). Try the following sketch to see an illustration of this:
```
import gsw, numpy
from timeit import default_timer as timer
d = numpy.array(range(2000))
lat = 0
start = timer()
for z in d:
gsw.p_from_z(-z, lat)
end = timer()
print end-start
start = timer()
gsw.p_from_z(-d, lat)
end = timer()
print end-start
```
As usual, @s-good let me know what you think.
=> precompute pressures in en_background

qctests/CSIRO_wire_break.py, tests/CSIRO_wire_break_validation.py
It occurs to me that `util.dbutils.db_to_df`'s `filter_on_wire_break` option seems to assume that `CSIRO_wire_break` test flags all levels that are affected by a wire break; I'm not sure that it does. Most profiles flagged by the wire break test look qualitatively like:
But [the wire break reference](https://journals.ametsoc.org/doi/full/10.1175/JTECHO539.1) and our qc test only check the very last level - meaning that the db util is only filtering out, at most, the last level of a profile. Is that really what we want, or do we want to filter out all the red points in the above figure? (the unlabeled color scale is originator qc code).
This PR tries to flag all such points at the end of a profile by flagging:
- all the levels in a consecutive run from the end that fall outside of …
=> more thorough wire break test

qctests/EN_increasing_depth_check.py
@s-good, this is what I mentioned to you over email earlier today - this simple fix reflects what I ran to get the results we'll likely present in Oostende. You mentioned checking single level profiles for depths >=0, which I will have a look at presently, as well as adding some unit tests for this edge case.
=> dont flag single level profiles in EN_increasing_depth

qctests/AOML_constant.py, tests/AOML_constant_check.py
xbt perf check:
```
No parameters to load for AOML_constant
NAME OF TEST   FAILS     TPR     FPR     TNR     FNR
Truth   10172  100.0%    0.0%  100.0%    0.0%
AOML_constant     248    0.4%    0.4%   99.6%   99.6%
```
=> AOML_constant check

qctests/AOML_gradient.py, tests/AOML_gradient_check.py
the first of many AOML tests to be ported over from ftp://ftp.aoml.noaa.gov/phod/pub/bringas/XBT/AQC/AOML_AQC_2018/codes/.
quickie XBT performance:
```
NAME OF TEST   FAILS     TPR     FPR     TNR     FNR
Truth   10172  100.0%    0.0%  100.0%    0.0%
AOML_gradient    8233   56.9%    4.3%   95.7%   43.1%
```
=> AOML gradient test

build-db.py, qctests/EN_track_check.py
I've been fiddling with `EN_track` since Oostende to try and address issues discussed in #225 and #226. While this PR doesn't quite get us where I'd like to be, it makes some necessary improvements:
- Per @BoyerWOD's comments, cruises are identified including the 2-character country code, and profiles reporting aircraft platforms are dropped. Note that profiles reporting country code 99 (unidentified / error) are not considered at this time.
- Previous implementation of this test checked the suitability of the first profile passed to the test for assessment by EN_track, but didn't impose the same conditions on the collection of other profiles found to share a track with the first; this was an oversight, corrected here.
- Speed thresholds are doubled, to 30 m/s for ships and 4 m/s for …
=> preliminary improvements to en-track

analyse-results.py, qctest_groups.csv, qctests/ICDC_aqc_07_spike_check.py, util/dbutils.py
This pull request is an attempt to implement finding a best QC set by enforcing the use of at least one from each type of QC test that is designed to catch particular error modes (such as a spike). Updates are:
- Read QC group definition from a CSV file; this allows filtering the data using the results of particular tests.
- Five QC tests were 'pre-chosen': wire breaks test, checks that location and time data are plausible, check that depth is zero or greater, and reject of XBT levels < 3.6 m (which is a standard thing to do for XBTs).
- The best test from each QC group (defined as being the closest to 100% TPR and 0% FPR) is selected. 
- Other tests are then added using the existing method or trying to maximise the gradient of the ROC curve.
- An issue was identified with the ICDC spike …
=> Best QC set using at least one from each type of test

catchall.py
Here is my algorithm for choosing combinations of QC tests that capture all bad profiles with a minimum FPR, which I mention in #225; this is optimized for aggressively pursuing 100% TPR, without relying on pre-defined classes of tests. I'm posting this mostly for comparison and record's sake - happy to go with @s-good's method, though as I describe below I think both suffer from the same underlying problem.
Running on our QuOTA sample constructed per our Oostende results, this produces a test combination list of:
```
"tests": [
"EN_constant_value_check",
"Argo_global_range_check",
"EN_range_check",
"ICDC_aqc_06_n_temperature_extrema",
"CSIRO_wire_break",
"CoTeDe_spike",
"ICDC_aqc_07_spike_check",
"Argo_spike_test",
"CSIRO_depth",
"EN_increasing_depth_check", …
```
=> draft of data-driven algo to catch all bad profiles

build-db.py, filter-db.py
@s-good this is the filtering flag I mentioned via email earlier today, and what I used producing my results for Oostende; the db flag tracks whether a profile has originator flags at depths shallower than those flagged as a wire break.  `filter-db.py` creates a downsampled table with equal numbers of good and bad profiles, as a somewhat naive training sample construction.
Per your suggestion, we can make decisions about sampling later - but it'd be nice for the production run to have this flag present.
=> add flag to db for selecting good / bad profiles

AutoQC.py, build-db.py
These two changes are:
1. Set up the build-db.py program to ignore originator_profile_type (as QuOTA does not have this set) and only read data for months 1, 2, 3 and 6 (the months fully manually quality controlled in QuOTA). This is selected by adding an optional configuration keyword to the end of the calling string.
2. A small modification to AutoQC.py to allow processing to be run in batches. This is helpful when there is a limit on how long a process is allowed to run as it makes it easy to break the processing into shorter batches.
=> Modifications for QuOTA production run

build-db.py
We recently changed build-db.py to allow setting a logical from the command line. The syntax used looked like it should work:
`bool(sys.argv[3])`
However, it turns out that anything except an empty string gets turned into True by this.
This is an option for an alternative:
`ast.literal_eval(sys.argv[3])`
It uses the ast built in Python module. It works, but I don't know if this is the best solution.
=> Fix interpretation of True/False in command line

util/AOMLinterpolation.py
@s-good in our recent data run, I see a grand total of zero flags raised by AOML climatology. Digging in a bit, it seems that `nearest_indices` in `util/AOMLinterpolation.py` is using scipy's kdtree to ask for the 100 closest lat/long points from a pre-determined lattice closest to the profile's position, but there's no protection to make sure there are actually at least 100 points in the lattice to return. Ask for more neighbors than the lattice has, and kdtree just returns a bunch of infs (see example below). Also, why 100? It seems to only take the closest 1.
This PR forces a sensible return from kdtree, and only asks for the nearest neighbor.
Minimum example of bad behavior in kdtree:
```
import numpy as np
from scipy.spatial import cKDTree
ll = …
```
=> dont ask for more points than possible from kdtree

util/dbutils.py
@s-good sorry I've been a bit quiet for a while, I was chasing around why I was getting a bunch of surface XBTs bloating my false negatives when they should have just been masked out - turns out that for multi-action filters (like the default one), the list of profiles dropped for having no valid levels after filtration was being reset every action - so only the last action actually causes profiles to get dropped in `db_to_df`.
Also, I've turned the drop list into a set, just to make sure we don't try and drop the same thing twice (especially dangerous when dropping by table row ID).
=> make sure drop list isn't reset every action in db_to_df

qctests/IQUOD_bottom.py, util/main.py
~work in progress - not ready for merge~
Here's a sketch of a QC test that flags any level deeper than the ocean floor at the reported lat/long. Of the roughly 300 bad quota profiles we are currently failing to flag in our test sample (ie false negatives), about 50 are flagged by this test. This will likely be a part of the 'pre-cleaning' step where we discount obviously bad levels, like what we currently do for wire breaks.
While very successful at eliminating a large class of our remaining false negatives, this implementation relies on the google maps API to determine the depth of the sea floor, which is cost prohibitive ($5 USD / 1000 requests); a mergable implementation needs to be able to make this determination for free. @BoyerWOD, I see that NOAA provides bathymetry data at ex …
=> testing for bottom hits

.travis.yml
Unfortunately I was not successful in rebuilding our environment from scratch from `install.sh` and our Dockerfile; luckily we have that environment captured for posterity as `iquod/autoqc:ubuntu-16.04`.
From that image, we can build patch environments that add on things like the climatology file ICDC_10 needs in order for #247 to pass. We should and will document that patch lineage in the Docker repo that holds those images.
=> patch environment for new icdc climatology

qctest_groups.csv, qctests/IQuOD_gross_range_check.py, tests/IQuOD_gross_range_check_validation.py
This check was suggested by @castelao as a pre-filter to remove gross outliers before the other QC checks are run. It is similar to other global range checks but has an extreme range so only obviously bad data are excluded.
=> Gross range check

AutoQC.py, qctests/AOML_spike.py, qctests/Argo_impossible_date_test.py, qctests/Argo_impossible_location_test.py, qctests/EN_background_check.py, qctests/EN_constant_value_check.py, qctests/EN_increasing_depth_check.py, qctests/EN_stability_check.py, qctests/EN_track_check.py, qctests/minmax.py, tests/dbutils_validation.py, util/dbutils.py
This pull request does some tidying in preparation for our production run:
- Remove warning message in AOML_spike.py due to using numpy.median on a masked array (the mask is already checked for missing data prior to the use of numpy.median so the warning message is not useful). Using numpy.ma.median prevents the warning being printed. Numpy.ma.mean was also used in place of numpy.mean, but I don't think this was giving warnings.
- Try to make all tests return a QC result for all levels. Some QC tests such as the track check were just returning a single value, which is inconsistent with what most of the tests are doing.
- Fix an issue that was occurring for the EN_std_level_bkg_and_buddy_check, which tries to use previously cached results from other tests. The code wasn't checking whether …
=> Tidying up

qctests/AOML_gradient.py, qctests/EN_background_check.py, qctests/EN_spike_and_step_check.py, qctests/ICDC_aqc_01_level_order.py, tests/EN_spike_and_step_check_validation.py
Two changes to remove warnings/errors during productions runs:
1. Check for zero depth change in AOML_gradient to avoid divide by zero. I wasn't sure what to do in this situation, but went with setting the QC check to ignore pairs of levels with zero depth change as there are other QC checks that are designed to deal with this kind of problem.
2. Remove dropping of tables that store data produced by QC checks such as EN_background. This causes problems if running in batches as it deletes results from previous batches that are needed by the EN_std_level_bkg_and_buddy_check.
During investigating 2 I noticed something about the util/main.dbinteract function, which is that it doesn't call the database commit function. According to the sqlite3 documentation, this is needed else changes made to …
=> Further tidying

cotede_qc/cotede_test.py, qctests/EN_std_lev_bkg_and_buddy_check.py
Two fixes to prevent errors if there are missing values in the date information provided with a profile:
- Remove testing for year < 1900 in cotede_qc.py. Looking back into the code history, this was included because datetime.datetime.strftime could not handle dates before 1900, but as stated [here](https://docs.python.org/3/library/datetime.html#technical-detail) it has been able to do this since version 3.3. Therefore, we can safely remove these lines of code since AutoQC is using Python 3.6.
- In EN_std_level... check that year, month and date are not None before comparing them to integers.
=> Fix issues handling times

analyse-results.py, catchall.py, qctest_groups.csv, qctests/EN_track_check.py, tests/dbutils_validation.py, util/dbutils.py
Updates mainly to the analysis routines. In particular:
- Add in a simpler version of the code in analyse-results.py. Apart from simplifying the code, the main difference is to force selection of QC checks in a particular order e.g. pick a range check, then a climatology check etc. This was implemented following feedback from colleagues.
- Implement two extra features in db_to_df:
1) When removing levels flagged by a particular test, allow additional levels around the flagged level to be removed also. This handles the situator where a QC operator or automatic QC test makes slightly different decisions on which levels to flag for the same issue.
2) Allow removal of levels deeper than a rejected level if it is an XBT. This may be done as once an XBT fails, the rest of the profile may be …
=> Production2021 updates

install.sh
Upgrade to oceansdb to solve an issue that was encountered with a small number of profiles.
Does the version number need changing anywhere else or is install.sh the only place it is set?
=> Upgrade to oceansdb
